# Generated by Django 4.1 on 2022-09-15 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=12)),
                ("isActive", models.BooleanField(default=False)),
                ("DateCreated", models.DateTimeField(auto_now_add=True)),
                ("DateModified", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "master",},
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Role", models.CharField(max_length=10)),
            ],
            options={"db_table": "userrole",},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProfileImage",
                    models.FileField(default="avatar.png", upload_to="profiles/"),
                ),
                ("FullName", models.CharField(blank=True, default="", max_length=30)),
                (
                    "Gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=10
                    ),
                ),
                ("Mobile", models.CharField(blank=True, default="", max_length=10)),
                ("BirthDate", models.DateField(default="1990-01-01")),
                ("Country", models.CharField(blank=True, default="", max_length=30)),
                ("State", models.CharField(blank=True, default="", max_length=30)),
                ("City", models.CharField(blank=True, default="", max_length=30)),
                ("Address", models.CharField(blank=True, default="", max_length=30)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kmarketapp.master",
                    ),
                ),
            ],
            options={"db_table": "userprofile",},
        ),
        migrations.AddField(
            model_name="master",
            name="UserRole",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kmarketapp.userrole"
            ),
        ),
    ]
